name: Build and Test

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build API Dockerfile
      run: docker build -f src/Torresmo.Api/Dockerfile .
